---
version: "3.5"
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: ./deployment/prometheus/config.yml
        target: /etc/prometheus/prometheus.yml
    networks:
      - temporal-network
  grafana:
    image: grafana/grafana
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 8085:3000
    volumes:
      - type: bind
        source: ./deployment/grafana/config.ini
        target: /etc/grafana/config.ini
      - type: bind
        source: ./deployment/grafana/provisioning
        target: /etc/grafana/provisioning
      - type: bind
        source: ./deployment/grafana/dashboards
        target: /var/lib/grafana/dashboards
    networks:
      - temporal-network

networks:
  temporal-network:
    name: temporal-network
    external: true
